### ISSUE TITLE
travis build artifacts are not available in deploy stage

### ISSUE THREAD

**Issue by marcofranssen** [marcofranssen/gothermostat#1]
As Travis is not persisting the artifacts of both the nodejs and go build stages the release will not contain all the build artifacts.

A solution for persisting the artifacts in between stages is required. to have proper releases automatically being released.

**Comment by Dynacommerce** [comment]
Correct. If im correct Travis runs each stage in a fresh env so you need to persist it on your own. Maybe S3 is an option?
